version: "3"
services:

  project_Viewer_db:
    container_name: project_Viewer_db
    image: 'mysql'
    environment:
      - 'MYSQL_DATABASE=ms_gprojeto_db'
      - 'MYSQL_PASSWORD=mh8q23pr99'
      - 'MYSQL_ROOT_PASSWORD=mh8q23pr99'
      #- 'MYSQL_USER=admin'
    ports:
        - 3306:3306
    volumes:
      - Database:/app/db/project_Viewer_db

  project_viewer_api:
    build: /API
    container_name: project_Viewer_api
    ports:
      - 8080:8080
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://project_Viewer_db:3306/project_Viewer_db?createDatabaseIfNotExist=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=mh8q23pr99
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - spring.servlet.multipart.max-file-size=200MB
      - spring.servlet.multipart.max-request-size=200MB
      - app.caminhoImagem=/app/
      - app.caminhozip=/app/Zip/
    depends_on:
      - project_Viewer_db
    volumes:
      - Upload:/app/
      - Uploadzip:/app/Zip/
    restart: on-failure

    

volumes:
  Upload:
  Uploadzip:
  Database: